### ISSUE TITLE
it's wrong to use strcmp to comapre a number with a string [in Statistical/primitivesCleanUp.m]

### ISSUE THREAD

**Issue by drinkcor** [rojas70/RCBHT#5]
strcmp(statData(i,GRAD_LBL),gradLabels(PIMP,:))

statData(i,GRAD_LBL) is a number, while gradLabels(PIMP,:) is a string. we shouldn't compare them directly. So we should put these codes inside primitivesCleanUp.m and remove gradLabels parameter from this function.

%   % CONSTANTS FOR gradLabels (defined in fitRegressionCurves.m)
    BPOS            = 1;        % big   pos gradient
    MPOS            = 2;        % med   pos gradient
    SPOS            = 3;        % small pos gradient
    BNEG            = 4;        % big   neg gradient
    MNEG            = 5;        % med   neg gradient
    SNEG            = 6;        % small neg gradient
    CONST           = 7;        % constant  gradient
    PIMP            = 8;        % large pos gradient 
    NIMP            = 9;        % large neg gradient
    %NONE            = 10;       % none

     if( ~intcmp(statData(i,GRAD_LBL),PIMP) && ...
                ~intcmp(statData(i,GRAD_LBL),NIMP) )

**Comment by rojas70** [comment]
Thanks!
